# Generated by Django 3.1.2 on 2020-12-02 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201202_0451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Category',
            new_name='categories',
        ),
    ]
