# Generated by Django 3.1.2 on 2020-12-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20201202_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(default=None, related_name='posts', to='posts.Category'),
        ),
    ]
