# Generated by Django 3.1.2 on 2020-12-04 01:45

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20201202_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default=None),
        ),
    ]
