# Generated by Django 3.1.2 on 2021-01-06 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_banner_categorybanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='post',
        ),
    ]
