# Generated by Django 3.1.1 on 2020-10-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('out of stock', 'out of stock'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Indoor', 'indoor'), ('Men Wares', 'Men Wares'), ('Women Wares', 'Women Wares'), ('Brand', 'Brand')], max_length=200, null=True),
        ),
    ]
