# Generated by Django 3.1.2 on 2020-11-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20201123_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hot',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
