# Generated by Django 3.1.2 on 2020-12-06 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_storeimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoreImage',
            new_name='ProductImage',
        ),
    ]
