# Generated by Django 3.1.2 on 2020-12-06 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20201206_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='products',
            new_name='product',
        ),
    ]
