# Generated by Django 3.1.2 on 2020-12-28 11:11

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20201227_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=None),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=None),
        ),
        migrations.AddField(
            model_name='product',
            name='specification',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=None),
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(default=None, related_name='product', to='store.Tag'),
        ),
    ]
