# Generated by Django 3.1.2 on 2020-12-28 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20201228_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tag',
            new_name='optional_tag',
        ),
    ]
