# Generated by Django 3.1.2 on 2020-12-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20201228_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='optional_tag',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(default=None, to='store.Tag'),
        ),
    ]
