# Generated by Django 3.1.2 on 2020-12-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
