# Generated by Django 3.1.2 on 2020-12-31 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
