# Generated by Django 3.1.2 on 2021-01-06 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20210106_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='topic',
            new_name='title',
        ),
    ]
